version: '3.8'

services:
  tplink-device-manager:
    image: lisankai93/tplink-device-manager:main
    container_name: tplink-device-manager
    # 临时使用 main 标签，等待推送后改为 latest
    # pull_policy: always
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_PORT=8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s